import { type MigrateDownArgs, type MigrateUpArgs } from '@payloadcms/db-postgres';

import { env } from '@/env/server';
import { rekeyEncryptedFields } from '@/payload/utils/rekey-encrypted-fields';

/**
 * Rotates PAYLOAD_SECRET for the AES-encrypted fields (clients.name, clients.phone_number,
 * form_submissions_data.value). Migration tracking guarantees it runs exactly once.
 *
 * The cipher (AES-256-CTR) is unauthenticated: a wrong PAYLOAD_SECRET_OLD silently re-encrypts
 * garbage and commits — no error, no rollback. There is no code-level guard, so follow the runbook:
 *   1. Back up the database.
 *   2. Dry-run on a copy — set PAYLOAD_SECRET (new) + PAYLOAD_SECRET_OLD (previous), run the
 *      migrations, and confirm clients and form-submission values still read correctly.
 *   3. Repeat the same env on production (a single deploy), then remove PAYLOAD_SECRET_OLD.
 *
 * With PAYLOAD_SECRET_OLD unset (every non-rotation deploy — dev, preview, and fresh databases
 * running migrations from scratch) this is a clean no-op.
 *
 * Future rotations: create a NEW migration (pnpm migrate:create) that calls rekeyEncryptedFields
 * the same way — do not edit this file; tracking will skip it as already applied.
 */
export async function up({ db, payload }: MigrateUpArgs): Promise<void> {
  await rekeyEncryptedFields({
    db,
    payload,
    oldSecret: env.PAYLOAD_SECRET_OLD,
    newSecret: env.PAYLOAD_SECRET,
  });
}

export async function down({ payload }: MigrateDownArgs): Promise<void> {
  // Re-encrypting with the old secret is impossible once it's removed; restore from a DB
  // backup to reverse.
  payload.logger.warn('Down migration for the PAYLOAD_SECRET re-key is a no-op.');
}
